[package]
authors = ["kaiser <1244713586@qq.com>"]
edition = "2018"
name = "kos"
version = "0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
rlibc = "1.0.0"
bootloader = "0.9.8"
